blogger/api/urls.py
from django.conf.urls import url 
#Import the format_suffix_patterns() for dynamic accept of requests for 
# JSON, XML, etc. API data response formats
from rest_framework.urlpatterns import format_suffix_patterns

from blogger.api import views 

urlpatterns = format_suffix_patterns (
[  url(r'^$', views.blogger_api_root, name="blogger_api_root"),
   url(r'^bloggers/$', views.BloggerListView.as_view(), name="blogger_list"),
   url(r'^blogs/$', views.BlogListView.as_view(), name="blog_list"),
   url(r'^blogposts/$', views.BlogPostListView.as_view(), name="blogpost_list"),
   url(r'^comments/$', views.CommentListAPIView.as_view(), name="comment_list"), 
   url(r'^blogcategories/$', views.BlogCategoryListView.as_view(), name="blogcategory_list"),
   url(r'^bloggers/(?P<page>[-\w]+)/$', views.BloggerDetailView.as_view(), name="blogger_detail"),
   url(r'^blogs/(?P<page>[-\w]+)/$', views.BlogDetailView.as_view(), name="blog_detail"),
   url(r'^blogposts/(?P<page>[-\w]+)/$', views.BlogPostDetailView.as_view(), name="blogpost_detail"),
   url(r'^blogcategories/(?P<page>[-\w]+)/$', views.BlogCategoryDetailView.as_view(), name="blogcategory_detail"),
   
   ]
)

blogger/urls.py
from django.conf.urls import url 
from blogger import views 

urlpatterns = [
    url(r'^$',views.home, name="home"),
    url(r'^about/$', views.about, name="about"),
    url(r'^contact/$', views.contact, name="contact"),
    url(r'^newsletter/$', views.newsletter, name="newsletter"),
    url(r'^legal/$', views.legal_terms, name="legal"),
    url(r'^comment/(?P<post_link>[-\w]+)/$', views.comment_on_post, name="comment"),

]

blogmatiq/urls.py
from django.conf.urls import url, include 
from django.contrib import admin
from socialite.api.views import blogmatiq_api_root 

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^auth/', include('django.contrib.auth.urls', namespace="auth")),
    url(r'^social/', include('social_django.urls', namespace="social")),
    url(r'^api/$', blogmatiq_api_root, name="blogmatiq_api_root"),
    url(r'^api-auth', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^socialite/', include('socialite.urls', namespace="socialite")),
    url(r'', include('blogger.urls', namespace="blogger")),
    url(r'^api/blogger/', include('blogger.api.urls', namespace="blogger_api")),
    url(r'^api/socialite/', include('socialite.api.urls', namespace='socialite_api')),
]

socialite/urls.py
from django.conf.urls import url 
from socialite import views

urlpatterns = [
   url(r'^$', views.home, name="home"),
   url(r'^facebook/(?P<page_url>[-\w]+)/$', views.facebook_share, name="share_on_facebook"),
   url(r'^twitter/(?P<page_url>[-\w]+)/$', views.twitter_share, name="share_on_twitter"),
   url(r'^linkedin/(?P<page_url>[-\w]+)/$', views.linkedin_share, name="share_on_linkedin"),
]

blogger/models.py
from __future__ import unicode_literals

from django.db import models
from django.utils import timezone
from django.utils.text import slugify 
from django.contrib.auth.models import User 


# Create your models here.
class Blogger(models.Model):
	user = models.OneToOneField(User, related_name="blogger", on_delete=models.CASCADE)
	bio = models.TextField(max_length=500)
	page = models.SlugField(max_length=100, blank=True)
	date_joined = models.DateTimeField(auto_now_add=True)
	last_updated = models.DateTimeField(blank=True, null=True, editable=False)


	def __str__(self):
		return "%s: %s" % (self.user.username, self.date_joined)

	def save(self, *args, **kwargs):
		if not self.page:
			user_names = self.user.first_name + ' ' + self.user.last_name
			self.page = slugify(user_names[:90])

		super(Blogger, self).save(*args, **kwargs)
"""
	@property
	def filterable_fields(self):
    	'''
		Returns a tuple of the provided model's filterable fields
		'''
		return ('user','bio','page',)

	@property
	def searchable_fields(self):
        '''
            Returns a tupled list of the the provided model's searchable fields
        '''
        return ('bio','user',)
"""

class Blog(models.Model):
	owner = models.ForeignKey(Blogger, related_name="blogs", on_delete=models.CASCADE)
	name = models.CharField(max_length=100)
	desc = models.TextField()
	page = models.SlugField(max_length=110, blank=True)
	date_created = models.DateTimeField(auto_now_add=True)
	last_updated = models.DateTimeField(null=True, blank=True, editable=False)

	def __str__(self):
		return "%s" % (self.name)

	def save(self, *args, **kwargs):
		if not self.page:
			self.page = slugify(self.name)
		super(Blog, self).save(*args, **kwargs)
"""
	@property
    def filterable_fields(self):
        '''
            Returns a tuple of the provided model's filterable fields
        '''
        return ('name','owner','active','page','date_created',)

    @property
    def searchable_fields(self):
        '''
            Returns a tupled list of the the provided model's searchable fields
        '''
        return ('name','desc',)
    		
"""
class BlogCategory(models.Model):
	name = models.CharField(max_length=100)
	desc = models.TextField(verbose_name="Description", max_length=350)
	page = models.SlugField(max_length=120, blank=True)
	blog = models.ForeignKey(Blog, related_name="categories", on_delete=models.CASCADE)

	class Meta:
		verbose_name = "Blog Category"
		verbose_name_plural = "Blog Categories"

	def save(self, *args, **kwargs):
		if not self.page:
			self.page = slugify(self.name)
		super(BlogCategory, self).save(*args, **kwargs)


	def __str__(self):
		return self.name \

	@property
	def filterable_fields(self):
		'''
		Hello
		'''
		return ('blog','name','page','blog__page',)
"""
    @property
    def searchable_fields(self):
        '''
            Returns a tupled list of the the provided model's searchable fields
        '''
        return ('blog__name','title','desc',)
"""
class BlogPost(models.Model):
	category = models.ForeignKey(BlogCategory, related_name="blog_posts", on_delete=models.CASCADE)
	title = models.CharField(max_length=100)
	page = models.SlugField(max_length=120, blank=True)
	body = models.TextField()
	posted_date = models.DateTimeField(auto_now_add=True)
	updated = models.DateTimeField(blank=True, null=True, editable=False)

	def __str__(self):
		return "%s => %s" % (self.title, self.category.name)

	@property
	def filterable_fields(self):
		'''
		Returns a tuple of the provided model's filterable fields
		'''
		return ('category','title','page','posted_date','updated','category__page',)

"""
    @property
    def searchable_fields(self):
        '''
            Returns a tupled list of the the provided model's searchable fields
        '''
        return ('title','body',)
"""
class Comment(models.Model):
	commenter = models.ForeignKey(User, related_name="comments", on_delete=models.CASCADE)
	subject = models.CharField(max_length=100)
	page = models.SlugField(max_length=120, blank=True)
	blog_post = models.ForeignKey(BlogPost, related_name="comments", on_delete=models.CASCADE)
	body = models.TextField(max_length=500)
	comment_date = models.DateTimeField(auto_now_add=True)

	def __str__(self):
		return "%s" % (self.subject)

	def save(self, *args, **kwargs):
		if not self.page:
			self.page = slugify(self.subject)
		super(Comment, self).save(*args, **kwargs)

blogmatiq/utils/models.py
def get_model_field_names(model, exclude_fields=None):
    model_fields = model._meta.get_fields()
    model_field_names = [field.name for field in model_fields]
    if exclude_fields:
        for i in exclude_fields:
            model_field_names.remove(i)
    return tuple(model_field_names)

blogger/api/views.py
from blogger.models import (
	Blogger, Blog, BlogCategory, BlogPost, Comment
)
from blogger.api.serializers import (
	BloggerSerializer, BlogSerializer, BlogCategorySerializer,
	BlogPostSerializer, CommentSerializer
	)
from django.http import Http404 
from rest_framework import viewsets, generics
from rest_framework.reverse import reverse 
from rest_framework.response import Response 

#Import the filter classes and backends to use with the Blogger API 
from django_filters.rest_framework import DjangoFilterBackend
from  rest_framework import filters as drf_filters 

#Authentication and Permission classes for access to the API endpoints
from rest_framework.decorators import (api_view, authentication_classes)
from rest_framework.permissions import (
	IsAdminUser, IsAuthenticated, IsAuthenticatedOrReadOnly, DjangoModelPermissions
)

from rest_framework.authentication import (
	SessionAuthentication, BasicAuthentication, TokenAuthentication
)



def get_object(model_name, page):
    """
    A utility function to do a get on any Django model using its 'url' field
    """
    try:
        model_name.objects.get(page=page)
    except Object.DoesNotExist:
        raise Http404

@api_view(['GET'])
#@authentication_classes((SessionAuthentication,TokenAuthentication,))
def blogger_api_root(request, format=None):
    """
    URL endpoint to serve as the API Root (landing page) of the Blogger app's API.
    """
    return Response({
            'bloggers': reverse('blogger_api:blogger_list', request=request, format=format),
            'blogs': reverse('blogger_api:blog_list', request=request, format=format),
            'blogcategories': reverse('blogger_api:blogcategory_list', request=request, format=format),
            'blogposts': reverse('blogger_api:blogpost_list', request=request, format=format)
        })

class BloggerListView(generics.ListCreateAPIView):
    queryset = Blogger.objects.all()
    serializer_class = BloggerSerializer
    #filter_fields = Blogger.filterable_fields
    #search_fields = Blogger.searchable_fields
    lookup_field = "page"

class BloggerDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Blogger.objects.all()
    serializer_class = BloggerSerializer
    lookup_field = "page"

class BlogListView(generics.ListCreateAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer
    #filter_fields = Blog.filterable_fields
    #search_fields = Blog.searchable_fields
    lookup_field = "page"

class BlogDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = Blog.objects.all()
    serializer_class = BlogSerializer 
    lookup_field = "page"

class BlogCategoryListView(generics.ListCreateAPIView):
    queryset = BlogCategory.objects.all()
    serializer_class = BlogCategorySerializer
    filter_fields = BlogCategory.filterable_fields
    #search_fields = BlogCategory.searchable_fields
    lookup_field = "page"
    filter_backends = (DjangoFilterBackend,)

class BlogCategoryDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = BlogCategory.objects.all()
    serializer_class = BlogCategorySerializer
    filter_fields = BlogCategory.filterable_fields
    filter_backends = (DjangoFilterBackend,)
    lookup_field = "page"

class BlogPostListView(generics.ListCreateAPIView):
    queryset = BlogPost.objects.all()
    serializer_class = BlogPostSerializer
    filter_backends = (DjangoFilterBackend,)
    filter_fields = BlogPost.filterable_fields
    #search_fields = BlogPost.searchable_fields
    lookup_field  = "page"

class BlogPostDetailView(generics.RetrieveUpdateDestroyAPIView):
    queryset = BlogPost.objects.all()
    serializer_class = BlogPostSerializer
    lookup_field = "page"
    filter_backends = (DjangoFilterBackend,)
    filter_fields = BlogPost.filterable_fields

class CommentListAPIView(generics.ListCreateAPIView):
    queryset = Comment.objects.all()
    serializer_class = CommentSerializer 
    lookup_field = "page"

blogger/views.py
from django.shortcuts import render
from django.http import HttpResponse, HttpResponseRedirect

# Create your views here.
PAGE_URL = "page-url-here"
def home(request):
    data = {
        "page_url": PAGE_URL
    }
    return render(request, "blogger/index.html", data)

def comment_on_post(request, post_link):
    data = {}
    return HttpResponse("Comment on %s " % (post_link))

def about(request):
    data = {
        'page_url': PAGE_URL
    }
    return render(request, "blogger/about.html", data)

def contact(request):
    data = {
         'page_url': PAGE_URL
    }
    return render(request, "blogger/contact.html", data)

def newsletter(request):
    data = {
         'page_url': PAGE_URL
    }
    return render(request, "blogger/newsletter.html", data)

def legal_terms(request):
    data = {
         'page_url': PAGE_URL
    }
    return render(request, "blogger/legal.html", data)

blogger/templates/blogmatiq/blogmatiq.html
<!DOCTYPE html>
{% load staticfiles %}
<head>
    <title>
        Blogmatiq (!) {% block title %} {% endblock title %}
    </title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/css/materialize.min.css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/latest/css/font-awesome.min.css" />
    <link rel="stylesheet" href="{% static 'blogmatiq/material.min.css' %}">
</head>

<body>

    <!-- Always shows a header, even in smaller screens. -->
<div class="mdl-layout mdl-js-layout mdl-layout--fixed-header">
    <header class="mdl-layout__header">
        <div class="mdl-layout__header-row">
            <!-- Title -->
            <a href="{% url 'blogger:home' %}" class="white-text center-align">
              <span class="mdl-layout-title">
                Blogmatiq
              </span>
            </a>
            <!-- Add spacer, to align navigation to the right -->
            <div class="mdl-layout-spacer"></div>
            <!-- Navigation. We hide it in small screens. -->
            <nav class="mdl-navigation mdl-layout--large-screen-only  teal">
                <a class="mdl-navigation__link" href="{% url 'blogger:home' %}">Blogs</a>
                <a class="mdl-navigation__link" href="">Register</a>
                <!-- a class="mdl-navigation__link" href="">Link 3</a>
                <a class="mdl-navigation__link" href="">Link 4 </a>
                <a class="mdl-navigation__link" href="">Link 5 </a -->
                <!--DROPDOWN AUTH MENU -->
                {% if user and not user.is_anonymous %}
                  <a class="mdl-navigation__link" href="{% url 'auth:logout' %}?next={{request.path}}">Logout </a>
                {% else %}
                <!-- Simple Select -->
                    <div class="mdl-textfield mdl-js-textfield getmdl-select">
                        <input type="text" value="" class="mdl-textfield__input" id="social_auth" readonly>
                        <input type="hidden" value="" name="social_auth">
                        <label for="social_auth" class="mdl-textfield__label white-text">Login</label>
                        <ul for="social_auth" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                            <li class="mdl-menu__item" data-val="facebook">
                              <a href="{% url 'social:begin' 'facebook' %}?next={{request.path}}" class="purple btn btn-social-icon btn-facebook">
                                <span class="fa fa-facebook"></span>
                                Sign in with Facebook
                              </a>
                            </li>
                            <li class="mdl-menu__item" data-val="twitter">
                              <a href="{% url 'social:begin' 'twitter' %}?next={{request.path}}" class="btn btn-social-icon btn-twitter">
                                <span class="fa fa-twitter"></span>
                                Sign in with Twitter
                              </a>
                            </li>
                            <li class="mdl-menu__item" data-val="linkedin">
                              <a href="{% url 'social:begin' 'linkedin-oauth2' %}?next={{request.path}}" class="btn btn-social-icon btn-linkedin">
                                <span class="fa fa-linkedin"></span>
                                Sign in with Linkedin
                              </a>
                            </li>
                        </ul>
                    </div>

                  {% endif %}
                <!--END DROPDOWN AUTH MENU -->
            </nav>
        </div>
    </header>
<div class="mdl-layout__drawer">
  <a href="{% url 'blogger:home' %}" class="black-text center-align">
    <span class="mdl-layout-title">
      Blogmatiq
    </span>
  </a>
    <nav class="mdl-navigation teal">
      <a class="mdl-navigation__link" href="{% url 'blogger:home' %}">Blogs</a>
      <a class="mdl-navigation__link" href="">Register</a>
      <!-- a class="mdl-navigation__link" href="">Link 3</a>
      <a class="mdl-navigation__link" href="">Link 4 </a>
      <a class="mdl-navigation__link" href="">Link 5 </a -->
      <!--DROPDOWN AUTH MENU -->
      {% if user and not user.is_anonymous %}
        <a class="mdl-navigation__link" href="{% url 'auth:logout' %}?next={{request.path}}">Logout </a>
      {% else %}
      <!-- Simple Select -->
          <div class="mdl-textfield mdl-js-textfield getmdl-select">
              <input type="text" value="" class="mdl-textfield__input" id="social_auth" readonly>
              <input type="hidden" value="" name="social_auth">
              <label for="social_auth" class="mdl-textfield__label white-text">Login</label>
              <ul for="social_auth" class="mdl-menu mdl-menu--bottom-left mdl-js-menu">
                  <li class="mdl-menu__item" data-val="facebook">
                    <a href="{% url 'social:begin' 'facebook' %}?next={{request.path}}" class="purple btn btn-social-icon btn-facebook">
                      <span class="fa fa-facebook"></span>
                      Sign in with Facebook
                    </a>
                  </li>
                  <li class="mdl-menu__item" data-val="twitter">
                    <a href="{% url 'social:begin' 'twitter' %}?next={{request.path}}" class="btn btn-social-icon btn-twitter">
                      <span class="fa fa-twitter"></span>
                      Sign in with Twitter
                    </a>
                  </li>
                  <li class="mdl-menu__item" data-val="linkedin">
                    <a href="{% url 'social:begin' 'linkedin-oauth2' %}?next={{request.path}}" class="btn btn-social-icon btn-linkedin">
                      <span class="fa fa-linkedin"></span>
                      Sign in with Linkedin
                    </a>
                  </li>
              </ul>
          </div>

        {% endif %}
      <!--END DROPDOWN AUTH MENU -->
    </nav>
</div>
<main class="mdl-layout__content">
    <div class="page-content"><!-- Your content goes here -->
        <div class="mdl-grid">

              {% block page_content %}

              {% endblock page_content %}

        </div>

        {% if comment_form %}
        <div class="mdl-grid">
          <div class="mdl-cell mdl-cell--8-col">
            <h6>
              Got comments? Let us know in the comments below. Thank you! :)
            </h6>
          </div>
          <div class="mdl-cell mdl-cell--5-col">
            <form class="" action="{% url 'blogger:comment' post_link %}" method="post">
              {% csrf_token %}
              {{ comment_form.as_p }}
              <input type="submit" name="submit" value="Submit Comment">
            </form>

          </div>
          
          {% if comments %}
          <div class="mdl-cell mdl-cell--9-col">

            {% for comment in comments %}
              <div class="mdl-card mdl-shadow--6dp mdl-cell mdl-cell--7-col left-align">
                <div class="mdl-card__title">
                  <h2 class="mdl-card__title-text">
                    On {{ comment.created_dt }}, {{ comment.commenter|title }} says:
                  </h2>
                </div>
                <div class="mdl-card__media">

                </div>
                <div class="mdl-card__supporting-text">
                  <p>
                    <b>
                      <i>
                        {{ comment.subject }}
                      </i>
                    </b>
                  </p>
                    {{ comment.body|safe }}
                </div>
                <div class="mdl-card__actions">

                </div>
              </div>
            {% endfor %}
          </div>
          {% endif %}

        </div>
        {% endif %}

    </div>


    {% block site_footer %}
      <div class="mdl-grid" style="margin-bottom:0px">
          <div class="mdl-cell mdl-cell--12-col">
                  <footer class="mdl-mini-footer lighten-x2 teal" style="height:5% !important;">
                    <div class="mdl-mini-footer__left-section">
                      <ul class="mdl-mini-footer__link-list white-text">
                        <li><a href="{% url 'blogger:about' %}">About Us</a></li>
                        <li><a href="{% url 'blogger:legal' %}">Privacy & Terms</a></li>
                        <li>
                            <a href="{% url 'blogger:contact' %}">
                              Contact Us
                            </a>
                        </li>
                        <li>
                              <a class="" href="{% url 'blogger:newsletter' %}">Newsletter</a>
                        </li>
                      </ul>
                    </div>
                  </footer>
          </div>
      </div>
    {% endblock site_footer %}

</main>



 {# % block smshare % #}
    <div id="Blogmatiq-social-media-share_model" class="fixed-action-btn horizontal">
        <a class="btn-floating btn-large red">
          <i class="large material-icons">share</i>
        </a>
        <ul>
          <li><a href="{% url 'socialite:share_on_facebook' page_url %}" class="btn-floating red"> <i class="fa fa-facebook"></i></a></li>
          <li><a href="{% url 'socialite:share_on_twitter' page_url %}" class="btn-floating yellow darken-1"><i class="fa fa-twitter"></i></a></li>
          <li><a href="{% url 'socialite:share_on_linkedin' page_url %}" class="btn-floating green"><i class="fa fa-linkedin"></i></a></li-->
        </ul>
      </div>

 {#  % endblock smshare % #}
</div>

  <script src="{% static 'Blogmatiq/js/jquery.min.js' %}"> </script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/materialize/0.100.2/js/materialize.min.js"></script>
  <script src="{% static 'Blogmatiq/js/material.min.js' %}"> </script>
  	<!-- Control Center for Material Kit: activating the ripples, parallax effects, scripts from the example pages etc -->
  <!--script src="{% static 'Blogmatiq/assets/js/material-kit.js' %}" type="text/javascript"></script-->


  <!-- Drip -->
  <script type="text/javascript">
    var _dcq = _dcq || [];
    var _dcs = _dcs || {};
    _dcs.account = '2490028';

    (function() {
      var dc = document.createElement('script');
      dc.type = 'text/javascript'; dc.async = true;
      dc.src = '//tag.getdrip.com/2490028.js';
      var s = document.getElementsByTagName('script')[0];
      s.parentNode.insertBefore(dc, s);
    })();
  </script>
  <!-- end Drip -->
</body>
</html>